name: my first ci pipeline
on:
 push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: welcome message
       run: echo " hello world "

     - name: list the files
       run: ls
  
